# Generated by Django 2.2 on 2019-04-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neicun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nname', models.CharField(max_length=255, verbose_name='名称')),
                ('nbrand', models.CharField(max_length=50, verbose_name='品牌')),
                ('ncapacity', models.CharField(max_length=50, verbose_name='内存')),
                ('nmodel', models.CharField(max_length=50, verbose_name='型号')),
                ('ntype', models.CharField(max_length=50, verbose_name='类型')),
                ('nspeed', models.CharField(max_length=50, verbose_name='速度')),
                ('napplicable', models.CharField(max_length=50, verbose_name='适应机型')),
                ('nprice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='价格')),
                ('nclick', models.IntegerField(default=0, verbose_name='点击量')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('njianjie', models.CharField(default='暂无', max_length=200, verbose_name='简介')),
                ('nkucun', models.IntegerField(default=500, verbose_name='库存')),
                ('nimgb1', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='图片')),
                ('nimgb2', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='图片')),
                ('nimgb3', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='图片')),
                ('nimgb4', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='图片')),
                ('nimgb5', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='图片')),
                ('nimgs1', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='图片')),
                ('nimgs2', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='图片')),
                ('nimgs3', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='图片')),
                ('nimgs4', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='图片')),
                ('nimgs5', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='图片')),
            ],
        ),
    ]
