# Generated by Django 2.0 on 2019-04-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_neicun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='类型')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
