# Generated by Django 2.0 on 2019-04-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=255, verbose_name='商品名称')),
                ('gbrand', models.CharField(default='未知', max_length=50, verbose_name='商品品牌')),
                ('gseries', models.CharField(blank=True, default='未知', max_length=50, null=True, verbose_name='商品系列')),
                ('gpicb1', models.ImageField(blank=True, null=True, upload_to='static/images/bijiben/lianxiang', verbose_name='商品图片')),
                ('gpicb2', models.ImageField(blank=True, null=True, upload_to='static/images/bijiben/lianxiang', verbose_name='商品图片')),
                ('gpicb3', models.ImageField(blank=True, null=True, upload_to='static/images/bijiben/lianxiang', verbose_name='商品图片')),
                ('gpicb4', models.ImageField(blank=True, null=True, upload_to='static/images/bijiben/lianxiang', verbose_name='商品图片')),
                ('gpicb5', models.ImageField(blank=True, null=True, upload_to='static/images/bijiben/lianxiang', verbose_name='商品图片')),
                ('gpics1', models.ImageField(blank=True, null=True, upload_to='static/images/bijiben/lianxiang', verbose_name='商品图片')),
                ('gpics2', models.ImageField(blank=True, null=True, upload_to='static/images/bijiben/lianxiang', verbose_name='商品图片')),
                ('gpics3', models.ImageField(blank=True, null=True, upload_to='static/images/bijiben/lianxiang', verbose_name='商品图片')),
                ('gpics4', models.ImageField(blank=True, null=True, upload_to='static/images/bijiben/lianxiang', verbose_name='商品图片')),
                ('gpics5', models.ImageField(blank=True, null=True, upload_to='static/images/bijiben/lianxiang', verbose_name='商品图片')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格')),
                ('gclick', models.IntegerField(default=0, verbose_name='点击量')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('gjianjie', models.CharField(default='暂无', max_length=200, verbose_name='简介')),
                ('gkucun', models.IntegerField(default=500, verbose_name='库存')),
                ('gcontent', models.TextField(default='暂无', verbose_name='详细介绍')),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=50, verbose_name='类型名称')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.TypeInfo', verbose_name='所属分类'),
        ),
    ]
